name: "stdout"
url: "http://www.bpace.info"
baseurl: ""
description: "A blog about coding and technology"
author: "Blaine Pace"
copyright: "MIT"
highlighter: rouge
markdown: kramdown
paginate: 3
relative_permalinks: false
exclude: [
  '.travis.yml',
  'vendor',
  'Gemfile',
  'Gemfile.lock',
  'new_post',
  'Rakefile',
  'README.md',
]
redcloth:
  hard_breaks: false
gems:
  - jekyll-sitemap
